apiVersion: batch/v1
kind: Job
metadata:
  name: practice-workload-identity
  namespace: $K8S_NAMESPACE
  labels:
    app: practice-workload-identity
spec:
  template:
    metadata:
      name: practice-workload-identity
      labels:
        app: practice-workload-identity
    spec:
      containers:
      - name: practice-workload-identity
        image: $DOCKER_IMAGE_NAME:latest
      restartPolicy: Never
